language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # PyPy versions
  - "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install tox-travis
# command to run tests
script: tox
